sudo: false
dist: trusty
group: deprecated-2017Q4
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/ggenzone/jekyll-theme dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle install
- bundle exec rake deploy
env:
  global:
    secure: gB7DFDowCaUXgl0n/wAjQUnTNdcso0xcgTn15HXXOgqMuZ+a9tvoWmbxKlf2P81de6kkpTDQtD4FyAqiuDtiNu/+7xhzKVGNUGTo48waUZdoGVXQauENTWBGo6OCn9v1WdMr3dkLr6h23XelB+j+/zGEy9tMSdblnUrXkv05u66fY2Y5FpaXm/7C4qXRq88neSsVXS1yyFax5sZ/j/owZE2dkfUtMmHtyDXYoS0egJzOXOM4UrGnTKb7JSNEA77SgEdhzEJIGId/XBhmG28YUn3dNGENr7Uc+33rxL1vgfUeF/mHfZPleM39RlR9aaZEGqOPXdyk0LhIl846lhUkCipQfE48ZTL2F0ZIiehYsd37rBYsmSM7i/sAA5VI8Q+tzF1tHNuYzaehp6UjMm+jZDq6vLV7WDoWosjYq5KaAMbs22piSztIAWlyWu4VAJO3tUm5kgHOIDJ5gT1IJnJkmVkbxrvlkLBUL/JDOKX3stl6ht6QV5S6ZPFtVbZWs7r5bVKN+5PrA4w9kVOg4ymfuVpT28RAF2QO8mfW4je5tZcI+TO9lwjKi+PrwHGsUqpH8bwYyeRrp6WbgepvCHNt/GqpUIpFe/8+ZKSwdrw/Vy+OVyZRQaAGs9wdDt63RHDGE4PbXQbRUYg+qDi802ZQxvUVMv+rMHjhRr6+DLZYA9g=
