sudo: false
dist: trusty
group: deprecated-2017Q4 # To fix NPM timeout errors
language: ruby
rvm:
- 2.4.3
if: branch = master OR repo =~ /-stage/
before_install:
- echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
- git submodule add https://github.com/ggenzone/jekyll-theme dependencies/jekyll
- gem update --system && gem install bundler && gem update bundler
- mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
script:
- bundle install
- rake buildAll
- rake publish
env:
  global:
    secure: ZEF1JqCrPvYUgMIzjBF2rU2rVEcUAoDYaW9wC5RPjltt/a3dJU+2NqAzZsGxQvcdTtXVXkJQCMG8n8RqSf+VojbYgLXXOjyJ0KmQ6+I0mDWMFf2XU3H11BTxeS26ckad/0L6CMbRVC6M71xbbNHtGHUQRrAGDIatoIgEveW0JeZK4PyV2/bXmHsRlcX87HF2FbwLQVeoYt90gtiKjJzHAA0htS7uNkuuxh1EwOaMjuxQ/LyBhcC1wjmqs4hS2QmSWI/o5w3zsNj9C2Jl/JzHgVLDwR20fHlbN96MvXQTwbRiug1NOTsFL+iL0Tiry3Wgtcv9pkebou9+vA8ziS2prqtAaOpdOEpktQp6/PR0RkmO7lu/ELdAN3L/sfRulLMjOK/3gG3yDIMF8KTXFfxNwuT842pSPKOP8/Zhu7R96HdyrJ2HIZAPmr3PR7HzdxJnLeCj1mZ4ul2HU8ffbS9eqxtxlI0/a6dGF/uyYNHVt7pWVED4xpZ32tKZjZ/4zlpQd39qidGS+qyT6KQZbw9ktNP2JzxQEDIMeOnEU5WhjncikFCgMNKiBo8ouz8p4run+JYG4TUlq0qWwkzqVSx86V2Qw1VF8hJHQ9RN9pqB17mk+Obp4SoJXSNg4q24Dv/FquBRQfU2dE0Vmu50d0WnlErXG0kwu7OzkmVnXJdckis=
